from mido import MidiFile

global MARGIN_OF_ERROR, LENGTH_WEIGHT, CHORD_WEIGHT, DOWNBEAT_WEIGHT, DISTANCE_WEIGHT, JAZZINESS_FACTOR, CHROMATIC_SCALE, CIRCLE_OF_FIFTHS
MARGIN_OF_ERROR = 0.005
CHORD_WEIGHT = [1.2,0.8,1]
LENGTH_WEIGHT = 1
DOWNBEAT_WEIGHT = 0.2
DISTANCE_WEIGHT = 0.1
JAZZINESS_FACTOR = 0
CHROMATIC_SCALE = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
CIRCLE_OF_FIFTHS = ['C', 'G', 'D', 'A', 'E', 'B', 'F#', 'C#', 'G#', 'D#', 'A#', 'F']
